import React, { useState, useEffect } from 'react';
import { api } from '../services/api';
import { Sparkles, Heart, Eye, ArrowUpRight, Search, Info } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const CommunityGallery = () => {
  const navigate = useNavigate();
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [searchQuery, setSearchQuery] = useState("");

  const fetchGallery = async () => {
    setLoading(true);
    try {
      const data = await api.getGallery();
      setItems(data);
    } catch (err) {
      console.error(err);
      setError("Failed to fetch gallery feed.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchGallery();
  }, []);

  const handleTryStyle = (item) => {
    navigate('/workspace', { 
      state: { 
        tryStyle: item.style_applied,
        originalUrl: item.original_url
      } 
    });
  };

  const filteredItems = items.filter(item => {
    const query = searchQuery.toLowerCase();
    return (
      item.project_title.toLowerCase().includes(query) ||
      item.username.toLowerCase().includes(query) ||
      item.style_applied.toLowerCase().includes(query)
    );
  });

  return (
    <div className="py-8 w-full max-w-6xl mx-auto px-4 text-white">
      {/* Title */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-10">
        <div>
          <h1 className="text-3xl font-black flex items-center gap-2">
            <Sparkles className="text-[var(--pixit-primary)] w-7 h-7" /> COMMUNITY CANVAS
          </h1>
          <p className="text-gray-500 text-xs mt-1">Explore trending artwork generated by PIXIT creators.</p>
        </div>

        {/* Search bar */}
        <div className="relative max-w-md w-full">
          <Search className="absolute left-4 top-3.5 w-4 h-4 text-gray-500" />
          <input 
            type="text" 
            placeholder="Search styles, titles, or creators..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full bg-[#111115]/80 border border-slate-800 rounded-xl py-3 pl-11 pr-4 text-sm text-white focus:border-[var(--pixit-primary)] outline-none transition"
          />
        </div>
      </div>

      {loading ? (
        <div className="flex flex-col items-center justify-center py-20">
          <div className="w-10 h-10 border-4 border-[var(--pixit-primary)]/20 border-t-[var(--pixit-primary)] rounded-full animate-spin mb-4"></div>
          <span className="text-gray-500 text-xs font-bold uppercase tracking-widest">Loading Showcase Feed...</span>
        </div>
      ) : error ? (
        <div className="bg-red-950/20 border border-red-500/30 text-red-500 p-6 rounded-2xl text-center">
          <p className="font-bold">{error}</p>
          <button 
            onClick={fetchGallery}
            className="mt-3 text-xs bg-red-500 text-white font-extrabold px-4 py-2 rounded-lg hover:bg-red-600 transition cursor-pointer"
          >
            Retry Connection
          </button>
        </div>
      ) : filteredItems.length === 0 ? (
        <div className="border border-dashed border-slate-800 rounded-3xl p-16 text-center bg-black/20">
          <h3 className="text-lg font-bold text-gray-400 mb-2">No stylized artwork found</h3>
          <p className="text-gray-600 text-xs mb-6 max-w-xs mx-auto">Try typing a different query or style filter above.</p>
          <button 
            onClick={handleTryStyle}
            className="bg-[var(--pixit-primary)] text-black font-extrabold text-xs uppercase px-5 py-2.5 rounded-xl cursor-pointer"
          >
            Create Your Own
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
          {filteredItems.map(item => (
            <div 
              key={item.stylization_id} 
              className="bg-[#111115]/60 border border-slate-800/80 rounded-2xl overflow-hidden group hover:border-[var(--pixit-primary)]/40 transition duration-300 flex flex-col justify-between"
            >
              {/* Image Frame */}
              <div className="relative aspect-square w-full overflow-hidden bg-black/40">
                <img 
                  src={item.processed_url} 
                  alt={item.project_title} 
                  className="w-full h-full object-cover transition duration-500 group-hover:scale-105"
                  loading="lazy"
                />
                
                {/* Style Badge */}
                <span className="absolute top-3 left-3 bg-[var(--pixit-primary)]/95 text-black text-[10px] font-black uppercase px-2.5 py-1 rounded-full shadow-lg">
                  {item.style_applied}
                </span>

                {/* Overlaid Action Button */}
                <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition duration-300 flex items-center justify-center backdrop-blur-xs">
                  <button 
                    type="button"
                    onClick={() => handleTryStyle(item)}
                    className="bg-white text-black font-extrabold text-xs px-5 py-3 rounded-xl hover:scale-105 transition flex items-center gap-1.5 cursor-pointer shadow-xl"
                  >
                    Try Style <ArrowUpRight className="w-4 h-4" />
                  </button>
                </div>
              </div>

              {/* Content Panel */}
              <div className="p-4 flex flex-col gap-2 bg-[#111115]/90">
                <div className="flex justify-between items-start gap-2">
                  <h3 className="font-extrabold text-sm text-white line-clamp-1 leading-snug">
                    {item.project_title}
                  </h3>
                  <span className="text-gray-500 text-[10px] whitespace-nowrap mt-0.5">
                    {new Date(item.created_at).toLocaleDateString()}
                  </span>
                </div>
                <div className="flex items-center justify-between mt-2 pt-2.5 border-t border-white/5">
                  <span className="text-xs text-gray-400 font-bold flex items-center gap-1">
                    👤 {item.username}
                  </span>
                  
                  {item.settings && (
                    <span className="text-[10px] text-gray-600 flex items-center gap-1">
                      <Info className="w-3 h-3" /> Intensity {(item.settings.intensity * 100).toFixed(0)}%
                    </span>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default CommunityGallery;
